

# This file was *autogenerated* from the file maass_levelone_driver.sage
from sage.all_cmdline import *   # import sage library

_sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_1en4 = RealNumber('1e-4')
from maass_levelone_computations import find_single_ev_linearized, find_evs
import sys
import time

def main():
    if len(sys.argv) < _sage_const_4 :
        print("  Usage:   sage progname R radius symtype")
        print("  example: sage progname 9.5 0.5 -1")
        sys.exit()
    R = float(sys.argv[_sage_const_1 ])
    radius = float(sys.argv[_sage_const_2 ])
    symtype = int(sys.argv[_sage_const_3 ])
    print("Searching for an eigenvalue in B({}, {}) with symtype {}".format(R, _sage_const_2 *radius, symtype))
    val = find_single_ev_linearized(R, radius, symtype, verbosity=_sage_const_2 )
    if val != None:
        print("{} is an eigenvalue.".format(val[_sage_const_0 ]))
    else:
        print("None found.")


def other_main():
    if len(sys.argv) < _sage_const_4 :
        print("  Usage:   sage progname R1 R2 symtype")
        print("  example: sage progname 9 11 -1")
        sys.exit()
    R1 = float(sys.argv[_sage_const_1 ])
    R2 = float(sys.argv[_sage_const_2 ])
    symtype = int(sys.argv[_sage_const_3 ])

    start = time.time()
    evs = find_evs(R1, R2, symmetry=symtype, verbosity=_sage_const_2 )
    print("Finished in {} seconds".format(time.time() - start))
    if evs:
        prev = evs[_sage_const_0 ]
        print('----- ev -----')
        print(prev[_sage_const_0 ])
        for val in prev[_sage_const_1 ]:
            print("  {}".format(val))
        print()

        for ev in evs[_sage_const_1 :]:
            if abs(ev[_sage_const_0 ] - prev[_sage_const_0 ]) < _sage_const_1en4 :
                continue
            print('----- ev -----')
            print(ev[_sage_const_0 ])
            for val in ev[_sage_const_1 ]:
                print("  {}".format(val))
            print()
            prev = ev

if __name__ == "__main__":
    #other_main()
    main()

