

# This file was *autogenerated* from the file singledriver.sage
from sage.all_cmdline import *   # import sage library

_sage_const_5 = Integer(5); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_0 = Integer(0)
from maass_sqfreelevel_computations import find_single_ev_linearized, find_evs, group_data
import sys
import time

def main():
    if len(sys.argv) < _sage_const_5 :
        print("  Usage:   sage progname N R   radius symtype")
        print("  example: sage progname 1 9.5 0.5 -1")
        sys.exit()
    level = int(sys.argv[_sage_const_1 ])
    R = float(sys.argv[_sage_const_2 ])
    radius = float(sys.argv[_sage_const_3 ])
    symtype = int(sys.argv[_sage_const_4 ])
    gd = group_data(level)
    print("Searching for an eigenvalue in B({}, {}) with symtype {}".format(R, _sage_const_2 *radius, symtype))
    val = find_single_ev_linearized(R, radius, None, gd, symtype, verbosity=_sage_const_2 , allsigns=True)
    if val != None:
        print("{} is an eigenvalue.".format(val[_sage_const_0 ]))
    else:
        print("None found.")


def other_main():
    if len(sys.argv) < _sage_const_5 :
        print("  Usage:   sage progname N R1 R2 diff symtype")
        print("  example: sage progname 1 9  11 0.1  -1")
        sys.exit()
    level = int(sys.argv[_sage_const_1 ])
    R1 = float(sys.argv[_sage_const_2 ])
    R2 = float(sys.argv[_sage_const_3 ])
    diff = float(sys.argv[_sage_const_4 ])
    symtype = int(sys.argv[_sage_const_5 ])

    start = time.time()
    gd = group_data(level)
    evs = find_evs(R1, R2, None, gd, diff=diff, symmetry=symtype, verbosity=_sage_const_2 , allsigns=True)

    print("## Finished in {} seconds".format(time.time() - start))
    if evs:
        prev = evs[_sage_const_0 ]
        print('#----- ev -----')
        print(prev[_sage_const_0 ])
        print(prev[_sage_const_2 ], "symtype {}".format(symtype))
        for val in prev[_sage_const_1 ]:
            print("  {}".format(val))
        print()

        for ev in evs[_sage_const_1 :]:
            #if abs(ev[0] - prev[0]) < 1e-4:
            #    continue
            print('#----- ev -----')
            print(ev[_sage_const_0 ])
            print(ev[_sage_const_2 ], "symtype {}".format(symtype))
            for val in ev[_sage_const_1 ]:
                print("  {}".format(val))
            print()
            prev = ev

if __name__ == "__main__":
    # other_main()
    main()

